config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create] do
      resources :comments, only: [:new, :create]
      resources :likes, only: [:new, :create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post

  after_save :update_comments_counter

  private

  def update_comments_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  belongs_to :post

  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true, allow_blank: false, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :author, class_name: 'User'
  has_many :comments, foreign_key: 'post_id'
  has_many :likes, foreign_key: 'post_id'

  after_save :update_posts_counter

  def recent_comments
    comments.order(created_at: :desc).limit(5)
  end

  private

  def update_posts_counter
    author.increment!(:posts_counter)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, allow_blank: false
  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  after_initialize :set_defaults

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  private

  def set_defaults
    self.posts_counter ||= 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :update_allowed_parameters, if: :devise_controller?

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |field|
      field.permit(:name, :photo, :bio, :posts_counter, :email, :password, :password_confirmation)
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
    @user = current_user
  end

  def create
    puts "comment params: #{comment_params}"
    @post = Post.find(params[:post_id] || params[:id])
    @comment = Comment.new(comment_params)
    @comment.author_id = current_user.id
    @comment.post = @post

    respond_to do |format|
      if @comment.save!
        format.html do
          redirect_to user_post_url(current_user, @post), notice: 'Comment was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index; end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def new
    @like = Like.new
    @user = current_user
  end

  def create
    @post = Post.find(params[:post_id] || params[:id])
    @like = Like.new(post_id: @post.id, author_id: current_user.id)
    @like.author_id = current_user.id

    respond_to do |format|
      if @like.save
        format.html { redirect_to user_post_url(current_user, @post), notice: 'Like was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @user = current_user
    @posts = @user.posts.includes(:comments)
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def create
    @post = Post.new(post_params)
    @post.author_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to user_post_url(current_user, @post), notice: 'Post was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :text, :comments_counter, :likes_counter)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<section class="container">
    <p class="post-title">Add New Comment :</p>
    <%= form_with model: @comment, url: user_post_comments_path, method: :post, local: true, class: "form-control" do |form| %>

    <div>
        <%= form.label :text %>
        <%= form.text_area :text, placeholder: "Type your comment here!", rows: 20, required: true,  class: "form-post-text" %>
    </div>

    <div>
        <%= form.submit "Save", class: "button" %>
    </div>
    <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link
    href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
    rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
    crossorigin="anonymous"
    />
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
</head>

<body>
<div  role="alert"><%= notice %></div>
<div  role="alert"><%= alert %></div>
<%= yield %>

<script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
  crossorigin="anonymous"
></script>
</body>
</html>

app/views/likes/new.html.erb
<section class="container">
    <%= form_with(model: @like, url: user_post_likes_path) do |form| %>
    <%= form.submit 'Add Like', class: "button" %>
    <% end %>
</section>

app/views/posts/index.html.erb
<section class="container">

    <div class="user-box">
        <img class="image-user" src=<%= @user.photo %> alt="user"/>
        <div class="user-info">
            <p class="user-name"><%= @user.name %></p>
            <p class="user-post">Number of posts: <%= @user.posts_counter%></p>
        </div>
    </div>

    <% @posts.each do |post| %>
        <div class="post-info">
            <%= link_to user_post_path(@user.id, post.id) do %>
                <p class="post-title">Post : <%= post.title %> by <%= post.author.name %></p>
                <p class="post-text"><%= post.text %></p>
                <p class="post-text-2">Comments: <span><%= post.comments_counter || 0 %>, Likes: <%= post.likes_counter || 0 %></span></p>
            <% end %>
        </div>

        <div class="comment-info">
            <% post.recent_comments.each do |comment| %>
                <p>
                    <span>
                        <%= comment.author.name %>:
                    </span>
                    <span>
                        <%= comment.text %>
                    </span>
                </p>
            <% end %>
        </div>

    <% end %>

    <div class="button-user">
        <%= button_to 'Add New Post', new_user_post_url(id: @user.id), method: :get, class: "button"%>
        <button class="button">
            Pagination
        </button>
    </div>

</section>

app/views/posts/new.html.erb
<section class="container">
    <p class="post-title">Add New Post :</p>
    <%= form_with model: @post, url: user_posts_path, method: :post, local: true, class: "form-control" do |form| %>

        <%= form.hidden_field :comments_counter, value: 0 %>
        <%= form.hidden_field :likes_counter, value: 0 %>

        <div class="mb-3 mt-3">
            <%= form.label :title %>
            <%= form.text_field :title, placeholder: "Title", required: true, class: "form-post-title" %>
        </div>

        <div>
            <%= form.label :text %>
            <%= form.text_area :text, placeholder: "Type your post here!", rows: 20, required: true,  class: "form-post-text" %>
        </div>

        <div>
            <%= form.submit "Save", class: "button" %>
        </div>
    <% end %>
</section>

app/views/posts/show.html.erb
<section class="container">
    <div class="post-info">
        <div class="post-title-box">
            <p class="post-title">Post : <%= @post.title %> by <%= @post.author.name %></p>
            <p class="comment-text">Comments: <%= @post.comments_counter || 0 %>, Likes: <%= @post.likes_counter || 0 %></p>
        </div>
        <p><%= @post.text %></p>
    </div>
    <div class="comment-info">
        <% @post.recent_comments.each do |comment| %>
            <div>
                <p>
                    <span>
                        <%= comment.author.name %>:
                    </span>
                    <span>
                        <%= comment.text %>
                    </span>
                </p>
            </div>
        <% end %>
    </div>
    <div class="button-user">
        <%= button_to "Back", user_path(@post.author, @post), method: :get, class: "button" %>
        <%= button_to "Add Comment", new_user_post_comment_path(@post.author, @post), method: :get, class: "button" %>
        <div >
            <%= form_with model: @like,  url: "/users/#{params['user_id']}/posts/#{params['id']}/likes", method: :post , local: true do |form|%>
                <%= form.submit "Like", class: 'button' %>
            <% end %>
        </div>
    </div>
</section>

app/views/users/index.html.erb
<section class="container">
    <% @users.each do |user| %>
        <div class="user-box m-3">
            <img class="image-user" src=<%= user.photo %> alt="user">
            <div class="user-info p-5">
                <p class="user-name"><%= link_to user.name, user %></p>
                <p class="user-post">Number of posts: <%= user.posts_counter%></p>
            </div>
        </div>
    <% end %>

</section>

app/views/users/show.html.erb
<section class="container flex flex--column">
    <div class="user-box">
        <img class="image-user" src=<%= @user.photo %> alt="user"/>
        <div class="user-info">
            <p class="user-name"><%= @user.name %></p>
            <p class="user-post">Number of posts: <%= @user.posts_counter%></p>
        </div>
    </div>
    <p class="user-bio"><%= @user.bio %></p>

    <% @user.recent_posts.each do |post| %>
        <%= link_to user_post_path(@user.id, post.id) do %>
        <div class="user-recent-post">
            <p class="post-title"><strong>Post</strong> : <%= post.title %></p>
            <p class="post-text"><%= post.text %></p>
            <h3 class="counters">Comments: <%= post.comments_counter %>
                Likes: <%= post.likes_counter %><h3>
        </div>
        <% end %>
    <% end %>

    <div class="button-user">
        <button class="button">
        <%= link_to "See all posts", user_posts_path(@user), class:"text-button" %>
        </button>
    </div>
</section>